project_id = "knyzkwgdmclcwvzhdmyk"

[functions.wapi-webhook]
verify_jwt = false

[functions.wapi-send]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.submit-b2b-lead]
verify_jwt = false

[functions.migrate-sales-materials]
verify_jwt = false

[functions.follow-up-check]
verify_jwt = false